name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      minio:
        image: quay.io/minio/minio
        ports:
          - 9000:9000
          - 9001:9001
        env:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: minio123
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Wait for MinIO
        run: |
          for i in {1..90}; do
            if curl -f http://localhost:9000/minio/health/live; then
              exit 0
            fi
            sleep 1
          done
          echo "MinIO is not available, skipping tests."
          exit 78  # exit code 78 means skipped in GitHub Actions

      - name: Run tests
        if: ${{ success() }}
        env:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: minio123
          MINIO_HOST_NAME: localhost
          MINIO_HOST_PORT: 9000
        run: pytest