name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
 test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Start MinIO
        env:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: minio123
        run: |
          docker run -d --name minio \
            -e MINIO_ROOT_USER=minio \
            -e MINIO_ROOT_PASSWORD=minio123 \
            -p 9000:9000 -p 9001:9001 \
            quay.io/minio/minio server /data --console-address ":9001"
      - name: Wait for MinIO
        run: |
          for i in {1..90}; do
            if curl -f http://localhost:9000/minio/health/live; then
              exit 0
            fi
            sleep 1
          done
          echo "MinIO is not available, skipping tests."
          exit 78
      - name: Run tests
        if: ${{ success() }}
        env:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: minio123
          MINIO_HOST_NAME: localhost
          MINIO_HOST_PORT: 9000
        run: pytest